// Copyright 2019-2022 PureStake Inc.
// This file is part of Moonbeam.

// Moonbeam is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Moonbeam is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Moonbeam.  If not, see <http://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_crowdloan_rewards
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-16, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/moonbeam
// benchmark
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// *
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./benchmarking/frame-weight-template.hbs
// --record-proof
// --json-file
// raw.json
// --output
// ./benchmarks/

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_crowdloan_rewards.
pub trait WeightInfo {
	#[rustfmt::skip]
	fn initialize_reward_vec(x: u32, ) -> Weight;
	#[rustfmt::skip]
	fn complete_initialization() -> Weight;
	#[rustfmt::skip]
	fn claim() -> Weight;
	#[rustfmt::skip]
	fn update_reward_address() -> Weight;
	#[rustfmt::skip]
	fn associate_native_identity() -> Weight;
	#[rustfmt::skip]
	fn change_association_with_relay_keys(x: u32, ) -> Weight;
}

/// Weights for pallet_crowdloan_rewards using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: CrowdloanRewards Initialized (r:1 w:0)
	// Storage: CrowdloanRewards InitializedRewardAmount (r:1 w:1)
	// Storage: CrowdloanRewards TotalContributors (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: CrowdloanRewards ClaimedRelayChainIds (r:1 w:1)
	// Storage: CrowdloanRewards UnassociatedContributions (r:1 w:0)
	// Storage: CrowdloanRewards AccountsPayable (r:1 w:1)
	#[rustfmt::skip]
	fn initialize_reward_vec(x: u32, ) -> Weight {
		(257_992_000 as Weight)
			// Standard Error: 11_000
			.saturating_add((46_187_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((4 as Weight).saturating_mul(x as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: CrowdloanRewards Initialized (r:1 w:1)
	// Storage: CrowdloanRewards InitRelayBlock (r:1 w:0)
	// Storage: CrowdloanRewards InitializedRewardAmount (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: CrowdloanRewards TotalContributors (r:1 w:0)
	// Storage: CrowdloanRewards EndRelayBlock (r:0 w:1)
	#[rustfmt::skip]
	fn complete_initialization() -> Weight {
		(28_913_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: CrowdloanRewards Initialized (r:1 w:0)
	// Storage: CrowdloanRewards AccountsPayable (r:1 w:1)
	// Storage: ParachainSystem ValidationData (r:1 w:0)
	// Storage: CrowdloanRewards InitRelayBlock (r:1 w:0)
	// Storage: CrowdloanRewards EndRelayBlock (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	#[rustfmt::skip]
	fn claim() -> Weight {
		(62_730_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: CrowdloanRewards AccountsPayable (r:2 w:2)
	#[rustfmt::skip]
	fn update_reward_address() -> Weight {
		(31_624_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: CrowdloanRewards UnassociatedContributions (r:1 w:1)
	// Storage: CrowdloanRewards ClaimedRelayChainIds (r:1 w:1)
	// Storage: CrowdloanRewards AccountsPayable (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	#[rustfmt::skip]
	fn associate_native_identity() -> Weight {
		(114_142_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: CrowdloanRewards AccountsPayable (r:2 w:2)
	#[rustfmt::skip]
	fn change_association_with_relay_keys(x: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 23_000
			.saturating_add((47_752_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: CrowdloanRewards Initialized (r:1 w:0)
	// Storage: CrowdloanRewards InitializedRewardAmount (r:1 w:1)
	// Storage: CrowdloanRewards TotalContributors (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: CrowdloanRewards ClaimedRelayChainIds (r:1 w:1)
	// Storage: CrowdloanRewards UnassociatedContributions (r:1 w:0)
	// Storage: CrowdloanRewards AccountsPayable (r:1 w:1)
	#[rustfmt::skip]
	fn initialize_reward_vec(x: u32, ) -> Weight {
		(257_992_000 as Weight)
			// Standard Error: 11_000
			.saturating_add((46_187_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((4 as Weight).saturating_mul(x as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(x as Weight)))
	}
	// Storage: CrowdloanRewards Initialized (r:1 w:1)
	// Storage: CrowdloanRewards InitRelayBlock (r:1 w:0)
	// Storage: CrowdloanRewards InitializedRewardAmount (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: CrowdloanRewards TotalContributors (r:1 w:0)
	// Storage: CrowdloanRewards EndRelayBlock (r:0 w:1)
	#[rustfmt::skip]
	fn complete_initialization() -> Weight {
		(28_913_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: CrowdloanRewards Initialized (r:1 w:0)
	// Storage: CrowdloanRewards AccountsPayable (r:1 w:1)
	// Storage: ParachainSystem ValidationData (r:1 w:0)
	// Storage: CrowdloanRewards InitRelayBlock (r:1 w:0)
	// Storage: CrowdloanRewards EndRelayBlock (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	#[rustfmt::skip]
	fn claim() -> Weight {
		(62_730_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: CrowdloanRewards AccountsPayable (r:2 w:2)
	#[rustfmt::skip]
	fn update_reward_address() -> Weight {
		(31_624_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: CrowdloanRewards UnassociatedContributions (r:1 w:1)
	// Storage: CrowdloanRewards ClaimedRelayChainIds (r:1 w:1)
	// Storage: CrowdloanRewards AccountsPayable (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	#[rustfmt::skip]
	fn associate_native_identity() -> Weight {
		(114_142_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: CrowdloanRewards AccountsPayable (r:2 w:2)
	#[rustfmt::skip]
	fn change_association_with_relay_keys(x: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 23_000
			.saturating_add((47_752_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}
